In [1]:
import pandas as pd

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\dir com\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\dir com\anaconda3\lib\site-packages (from kagglehub) (0.1.28)
Requirement already satisfied: packaging in c:\users\dir com\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\dir com\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\dir com\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\dir com\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\dir com\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dir com\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dir com\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dir com\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dir com\anaconda3\lib\site-packages (from requests->kagglehub) (2026.5.20)
Requirement already satisfied: colorama in c:\users\dir com\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download(
    "kaggle/recipe-ingredients-dataset"
)

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Dir com\.cache\kagglehub\datasets\kaggle\recipe-ingredients-dataset\versions\1

In [4]:
#seeing folders what is inside
import os

path = r"C:\Users\Dir com\.cache\kagglehub\datasets\kaggle\recipe-ingredients-dataset\versions\1"

print(os.listdir(path))

['test.json', 'train.json']

In [5]:
for file in os.listdir(path):
    print(file)

test.json
train.json

In [ ]:
import pandas as pd

Working With Json

In [7]:
df = pd.read_json(os.path.join(
    path,"train.json")
                 )

In [8]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [9]:
#Working with SQL

In [12]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\dir com\anaconda3\lib\site-packages (9.7.0)

In [13]:
import mysql.connector

In [14]:
#Please noted that if you do not have 'World' Dataset so it will give you error.
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='',
    database='world'
)

In [15]:
df = pd.read_sql_query(
    "SELECT * FROM city", conn
)

C:\Users\Dir com\AppData\Local\Temp\ipykernel_6152\2933025036.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

In [16]:
print(df.shape)
df.head()

(4079, 5)

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [17]:
#to avoid warnings we use
import warnings
warnings.filterwarnings("ignore")

In [18]:
df = pd.read_sql_query(
    "SELECT * FROM city WHERE CountryCode = 'USA'", conn
)

print(df)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]

In [19]:
df = pd.read_sql_query(
    "SELECT CountryCode, Name, Population FROM city", conn
)

print(df)

     CountryCode            Name  Population
0            AFG           Kabul     1780000
1            AFG        Qandahar      237500
2            AFG           Herat      186800
3            AFG  Mazar-e-Sharif      127800
4            NLD       Amsterdam      731200
...          ...             ...         ...
4074         PSE      Khan Yunis      123175
4075         PSE          Hebron      119401
4076         PSE        Jabaliya      113901
4077         PSE          Nablus      100231
4078         PSE           Rafah       92020

[4079 rows x 3 columns]