In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('movie.csv')

How big data is?

In [8]:
df.shape

(2457, 8)

How does the data look like?

In [9]:
df.head()
# df.sample(5)

,Unnamed: 0,id,original_name,overview,original_name.1,popularity,vote_average,vote_count
0,0,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,Dutton Ranch,143.0673,9.300,237
1,1,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,Off Campus,508.6964,9.000,422
2,2,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",Breaking Bad,171.4720,8.946,17895
3,3,209867,葬送のフリーレン,After the party of heroes defeated the Demon K...,葬送のフリーレン,64.5506,8.806,844
4,4,64010,응답하라 1988,Take a nostalgic trip back to the late 1980s t...,응답하라 1988,16.9599,8.800,213

What is the data type of col?

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       2457 non-null   int64
 1   id               2457 non-null   int64
 2   original_name    2457 non-null   object
 3   overview         2435 non-null   object
 4   original_name.1  2457 non-null   object
 5   popularity       2457 non-null   float64
 6   vote_average     2457 non-null   float64
 7   vote_count       2457 non-null   int64
dtypes: float64(2), int64(3), object(3)
memory usage: 153.7+ KB

In [ ]:
Are there any misssing values?

In [12]:
df.isnull().sum()

Unnamed: 0          0
id                  0
original_name       0
overview           22
original_name.1     0
popularity          0
vote_average        0
vote_count          0
dtype: int64

How does the data look mathematically?

In [13]:
df.describe()

        Unnamed: 0             id   popularity  vote_average    vote_count
count  2457.000000    2457.000000  2457.000000   2457.000000   2457.000000
mean   1228.000000   72341.924298    19.813015      7.687647    948.310134
std     709.419129   59489.281464    33.532672      0.577368   1683.789900
min       0.000000      36.000000     0.373300      3.500000    200.000000
25%     614.000000   26453.000000     5.586700      7.304000    281.000000
50%    1228.000000   67075.000000    10.658400      7.723000    445.000000
75%    1842.000000   96815.000000    21.225300      8.125000    905.000000
max    2456.000000  307423.000000   810.904100      9.300000  26994.000000

Are there any deplicate values?

In [14]:
df.duplicated().sum()

np.int64(0)

How is the correlation between cols?

In [ ]:
df.corr()

In [ ]:
df.corr().{'overview'}